# Generated by Django 3.1 on 2021-07-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('hourly_rate', models.IntegerField(null=True)),
                ('max_hrs', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs', models.IntegerField()),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.job')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('hourly_rate', models.IntegerField(null=True)),
                ('max_hrs', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs', models.IntegerField()),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('contractor', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('job_entries', models.ManyToManyField(to='employee.JobEntry')),
                ('machine_entries', models.ManyToManyField(to='employee.MachineEntry')),
            ],
        ),
    ]
