# Generated by Django 3.1 on 2021-07-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='hourly_rate',
            new_name='hourly_rent',
        ),
        migrations.AddField(
            model_name='timecard',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
