# Generated by Django 3.1 on 2021-07-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210718_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobentry',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.job'),
        ),
        migrations.AlterField(
            model_name='machineentry',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.machine'),
        ),
    ]
