# Generated by Django 3.1 on 2021-07-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210719_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobentry',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.job'),
        ),
        migrations.AlterField(
            model_name='machineentry',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.machine'),
        ),
    ]
