# Generated by Django 3.1 on 2021-07-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_druser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='druser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('contractor', 'contractor')], default='', max_length=15),
        ),
    ]
